// app/home/[slug]/page.js
import Cards from "@/components/Cards";
import React from "react";

const home = ({ params }) => {
  const { slug } = params;

  return (
    <>
      <div
        className="flex w-full h-full absolute bg-black q"
      >
        <div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
          <div>
            <span>"sdfghjkl"</span>
          </div>
        </div>
        <div className="card_container relative top-40 left-10">
          <Cards />
        </div>
      </div>
    </>
  );
};

export default home;
